language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
services:
- mysql
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer install
- bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1
script:
- composer test
before_deploy:
- echo 'Making deploy packages...'
- bash ./bin/cleanup.sh
- zip -r icon.zip ./
